platform :ios, '11.0'

target 'Smarter Bulb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smarter Bulb
    pod "HapticButton"
    pod "Slope"
    pod "CULColorPicker"
    pod "NotchyAlert"

end
