platform :ios, '11.0'

target 'Smarter Bulb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for Smarter Bulb
    pod "FlexColorPicker"
    pod "NotchyAlert"
    pod "IGColorPicker"
    pod 'SPStorkController'
    pod 'FaveButton'
    pod 'Cards', :git => 'https://github.com/PaoloCuscela/Cards.git'
    pod 'WhatsNew'
    pod 'AudioKit', '~> 4.0'
    pod 'Pastel'
    pod 'TactileSlider'

    post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
        '$(FRAMEWORK_SEARCH_PATHS)'
        ]
      end
    end
    
end
